elsassph/haxe-modular

- haxelib.json
- package.json
- tool/bin/split.js
- tool/src/Bundler.hx
Haxe JS sometimes emits code using `$global` as system-dependent scope (`window` in browser, `global` for nodejs...). This global scope is resolved and passed to the closure.
> Haxe global

- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/Parser.hx
Hot reloading enums causes issues because enum values comparison based on equality will fail after reloading.
For safety, move all enums in the main bundle.
> Hoist enums in main bundle

- runtime/index.js
If the type is missing, do not blow up on the haxe check, blow up later, then the console error message will be more informative.
This was caused by attempting to import a react component library. These were wrong:
```
@:jsRequire('react-digraph')
extern class GraphView extends react.ReactComponent  { }
@:jsRequire('react-digraph', 'GraphView')
extern class GraphView extends react.ReactComponent  { }
```
This was correct:
```
@:jsRequire('react-digraph', 'default')
extern class GraphView extends react.ReactComponent  { }
```
> If the type is missing, do not blow up on the haxe check.

- src/Bundle.hx
- src/RouteBundle.hx
- tool/bin/split.js
- tool/test/src/foo/Bar.hx
- tool/test/src/foo/Sub__M.hx
Haxe classes with underscore are transformed:
```
The_Class => The_$Class
The__Class => The_$_$Class
```
> Fixes: Classes with underscores not loaded #45

- bin/cmd.js
- build.hxml
- src/Bundle.hx
- src/Split.hx
- test.hxml
- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/Extractor.hx
- tool/src/Main.hx
- tool/src/Parser.hx
- tool/test/src/Main.hx
- tool/test/src/ServerMain.hx
- tool/test/src/Shared.hx
- tool/test/src/Unused.hx
- tool/test/src/foo/Gee.hx
- don't create Acorn locations if not required (eg. only for sourcemaps)
- don't clone and loop all the body nodes for each bundle (only main one)
- keep non-directly referenced code (previously was dropped); expecting that it is used through reflection so we're keeping them in the main bundle
> Performance improvement

- bin/cmd.js
- doc/advanced.md
- package.json
- readme.md
- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/Main.hx
- tool/test/src/test_hook.js
Expose a mechanism to provide to the `haxe-split` command a JS hook, allowing users to customise the identifiers graph to:
- control classes relations; can be used to break or create relations between classes, for example to solve the absence of relation between classes when Reflection is used,
- programmatically return an arbitrary number of classes to be split, without using `Bundle.load(Abc)` or `--macro Split.register('Abc')`.
Hook file(s) should be defined in the user's `package.json` under `config.haxe-split-hook`, as a string or array of string (paths to JS files):
```
"config": {
"haxe-split-hook": "script/my_hook.js"
}
```
```
"config": {
"haxe-split-hook": ["script/my_hook.js", "script/my_other_hook.js"]
}
```
> Graph processing hook

- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/Extractor.hx
- tool/src/Parser.hx
- tool/src/graphlib/Graph.hx
- tool/test/src/foo/Bar.hx
Bug: `$estr` and `$hxClasses` were either missing or duplicated in bundles.
Now they are correctly shared from the main bundle.
> Fix sharing of `$estr` and `$hxClasses` between main and modules.

- tool/bin/split.js
- tool/src/Parser.hx
- tool/test/src/foo/Sub__M.hx
- Incorrect sharing of Haxe value types (Int, Float,..) as opposed to native JS types (String, Date, Math).
- Missing matching of some cases of declarations (`var Float = Number`)
Fixes #54
> Fix casting of value types in modules

- tool/bin/split.js
- tool/src/Extractor.hx
- tool/src/Parser.hx
- tool/test/expect/node-debug-test9.json
- tool/test/expect/node-release-test7.json
- tool/test/expect/node-release-test9.json
- tool/test/expect/web-debug-test7.json
- tool/test/expect/web-debug-test9.json
- tool/test/expect/web-release-test7.json
- tool/test/expect/web-release-test9.json
- tool/test/src/CaseD.hx
- tool/test/src/Test9.hx
- tool/test/test-suite.js
It is possible to obtain a fully isolated module, which mean it doesn't get emitted.
Fixed Acorn parsing: simple walker skips the left side of assignment expressions, which means module identifiers were not linked to the call site of `Bundle.load`.
Added test case.
> Fix for isolated modules

- bin/cmd.js
- bin/kha.js
- bin/run.js
- src/Bundle.hx
- src/Split.hx
- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/Parser.hx
- tool/src/SourceMap.hx
- Added `-D modular_noprocess` to prevent modular to take control of the compiler's JS output - instead it only emits arguments for haxe-split.
- Added `-D modular_stub` to target non-JS targets with modular (API is inactive).
- Added helpers for Kha to hook in Kha build process.
- Note: splitting is disabled for `debug-html5` because there is no way to detect that the build is for Krom in Kode.
- Finishing the feature requires a way to detect (from the `khafile.js`) that it's an Electron target.
- To try this branch you need to install `haxe-modular` npm from git in the local `node_modules`.
Usage:
```
let project = new Project('Blocks');
project.addAssets('Assets/**');
project.addSources('Sources');
// Add modular library and split hook
require('haxe-modular/bin/kha').register(platform, …
```
> Kha toolchain support

- doc/library-usage.md
- src/Require.hx
Added `Require.jsExt = '.js'`, allowing to add a cache buster after the extension.
> Allow to customise the path of required modules

- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/HxSplit.hx
- tool/src/MinifyId.hx
- tool/src/Parser.hx
- tool/test/expect/web-debug-closure-testinterop.json
- tool/test/expect/web-debug-test1.json
- tool/test/expect/web-debug-test2.json
- tool/test/expect/web-debug-test3.json
- tool/test/expect/web-debug-test4.json
- tool/test/expect/web-debug-test5.json
- tool/test/expect/web-debug-test6.json
- tool/test/expect/web-debug-test7.json
- tool/test/expect/web-debug-test8.json
- tool/test/expect/web-debug-test9.json
- tool/test/expect/web-debug-testinterop.json
- tool/test/expect/web-release-closure-testinterop.json
- tool/test/expect/web-release-test1.json
- tool/test/expect/web-release-test2.json
- tool/test/expect/web-release-test3.json
- tool/test/expect/web-release-test4.json
- tool/test/expect/web-release-test5.json
- tool/test/expect/web-release-test6.json
- tool/test/expect/web-release-test7.json
- tool/test/expect/web-release-test8.json
- tool/test/expect/web-release-test9.json
- tool/test/expect/web-release-testinterop.json
- tool/test/src/CaseInterop.hx
- compress `$s.xxx` shared variables,
- share `require` stub with modules instead of duplicating it in every module.
Instead of having:
```javascript
// shared classes
$s.MyClass = MyClass; $s.OtherClass = OtherClass; ...
// imported class
var MyClass = $s.MyClass, OtherClass = $s.OtherClass, ...
```
The shared variables are compressed into:
```javascript
// shared classes
$s.a = MyClass; $s.b = OtherClass; ...
// imported classes
var MyClass = $s.a, OtherClass = $s.b, ...
```
Exceptions:
- class names of 2 characters or less (eg. `class R`),
- bundle entry point (eg. `MyClass` when `Bundle.load(MyClass)`)
> Size optimisation

- src/Bundle.hx
I ran into this while trying to port a project that used `-D js-classic` to use `haxe-modular` -- I assume that this flavor of output JS is simply not supported?
This PR gives a nice compile-time error to that effect. Without this PR, I got this confusing error during the split phase:
```
node_modules/haxe-modular/tool/bin/split.js:886
var _g = block.type;
^
TypeError: Cannot read property 'type' of undefined
at Object.walkRootFunction (node_modules/haxe-modular/tool/bin/split.js:886:17)
at Object.walkRootExpression (node_modules/haxe-modular/tool/bin/split.js:879:9)
at Object.walkProgram (node_modules/haxe-modular/tool/bin/split.js:871:9)
at Object.processInput (node_modules/haxe-modular/tool/bin/split.js:819:8)
at Object.Parser (node_modules/haxe-modular/tool/bin/split.js:809:7)
at …
```
> Add check for -D js-classic

- src/Bundle.hx
- tool/bin/split.js
- tool/src/Extractor.hx
- tool/test/expect/node-debug-test5.json
- tool/test/expect/node-release-test5.json
- tool/test/expect/web-debug-test5.json
- tool/test/expect/web-release-test5.json
- tool/test/src/Test5.hx
- Use string `startsWith` to match nodes with libs instead of EReg,
- Pre-evaluate nodes against libs instead of matching them during graph walking,
- Now support both a package or class name (also matched with `startsWith`).
> Libs optimisation

- tool/bin/split.js
- tool/src/Parser.hx
- tool/test/expect/node-debug-test10.json
- tool/test/expect/node-debug-test11.json
- tool/test/expect/node-release-test10.json
- tool/test/expect/node-release-test11.json
- tool/test/expect/web-debug-test10.json
- tool/test/expect/web-debug-test11.json
- tool/test/expect/web-release-test10.json
- tool/test/expect/web-release-test11.json
- tool/test/src/CaseE.hx
- tool/test/src/CaseF.hx
- tool/test/src/Test10.hx
- tool/test/src/Test11.hx
- tool/test/test-suite.js
Fixes #37 : Using `Object.defineProperty` / `Object.defineProperties` in a static `__init__` function breaks Modular because the code isn't attributed to the type.
> Support Object methods in static __init__

- tool/bin/split.js
- tool/src/Extractor.hx
The stack only wastes memory and in practice increases considerably the recursion depth when your VM doesn't have native support for it.
> Remove unfortunate "tail-call optimisation"

- extraParams.hxml
- package-lock.json
- package.json
- src/Split.hx
More consistent control of minification libraries with a hidden flag (e.g. `uglifyjs_slavemode`), so the libraries' normal disabling flag (`uglifyjs_disabled`) will work as expected.
Depends on both libraries accepting the flag PR.
+ make NPM uglifyjs dependency a dev-dependency (used only for tests)
> Minification flags

- tool/bin/split.js
- tool/src/Bundler.hx
- tool/src/Extractor.hx
New compact Haxe 4 enums declaration uses `$_` which is declared once and not shared. 
A new shared object is also introduced: `$hxEnums` which keeps references to declared Enums, like `$hxClasses` does.
Fix: declare `$_` in every child module in case an enum is declared.
> Haxe 4 preview enum breaking change

- tool/bin/split.js
- tool/src/Extractor.hx
In some cases, resolving a common parent of shared nodes can lead to infinite loop.
> Fix shareGraph infinite loop

- src/Bundle.hx
The current version generates something like `var _ = "...__BRIDGE__";`, which for the analyzer is an unused variable initialized to a constant, so it throws it out. Since there's no use for the var anyway, I chose to generate it as inline JavaScript, as the compiler will never touch that.
> Generate bridge marker in a way that analyzer won't remove it.
